/**
 * Scans src/assets/<page>/ for images and writes src/assets/files.generated.ts,
 * which statically imports each one under a "page/name" key (extension dropped).
 * Slots in src/assets/index.ts look files up by that key, so dropping in a correctly named file is enough.
 *
 * Runs automatically from next.config.ts (and keeps watching during `next dev`).
 * Manual run: `npm run assets`
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ASSETS_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "assets")
const OUT_FILE = path.join(ASSETS_DIR, "files.generated.ts")
const IMAGE_EXT = /\.(jpe?g|png|webp|avif|gif|svg)$/i

function collect() {
  const files = []
  for (const page of fs.readdirSync(ASSETS_DIR, { withFileTypes: true })) {
    if (!page.isDirectory()) continue
    for (const file of fs.readdirSync(path.join(ASSETS_DIR, page.name)).sort()) {
      if (IMAGE_EXT.test(file)) files.push(`${page.name}/${file}`)
    }
  }
  return files.sort()
}

export function generateAssets() {
  const files = collect()
  const keys = new Map()
  for (const file of files) {
    const key = file.replace(IMAGE_EXT, "")
    // Two files with the same name but different extensions: keep the first, warn about the rest.
    if (keys.has(key)) console.warn(`[assets] ${file} ignored: ${keys.get(key)} already uses "${key}"`)
    else keys.set(key, file)
  }

  const entries = [...keys.entries()]
  const output = [
    "// Generated by scripts/generate-assets.mjs. Do not edit: add or remove files in src/assets/<page>/ instead.",
    'import type { StaticImageData } from "next/image"',
    "",
    ...entries.map(([, file], i) => `import f${i} from "./${file}"`),
    "",
    "export const files: Record<string, StaticImageData> = {",
    ...entries.map(([key], i) => `  "${key}": f${i},`),
    "}",
    "",
  ].join("\n")

  const current = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : ""
  if (current !== output) {
    fs.writeFileSync(OUT_FILE, output)
    console.log(`[assets] ${entries.length} images registered`)
  }
}

export function watchAssets() {
  let timer
  fs.watch(ASSETS_DIR, { recursive: true }, (_event, name) => {
    if (!name || !IMAGE_EXT.test(name)) return
    clearTimeout(timer)
    timer = setTimeout(generateAssets, 150) // a paste fires several events
  })
}

if (process.argv[1] === fileURLToPath(import.meta.url)) generateAssets()
