// Generated by scripts/generate-assets.mjs. Do not edit: add or remove files in src/assets/<page>/ instead.
import type { StaticImageData } from "next/image"

import f0 from "./about/founder-ayush.png"
import f1 from "./about/founder-daksh.png"
import f2 from "./home/benefit-ingredients.jpg"
import f3 from "./home/benefit-smart-control.jpg"
import f4 from "./home/benefit-variety.jpg"
import f5 from "./home/diffusers-room.jpg"
import f6 from "./home/hero-poster.jpg"
import f7 from "./home/promo-harvest.jpg"
import f8 from "./home/promo-seasonal.jpg"
import f9 from "./home/promo-whole-home.jpg"
import f10 from "./home/space-cafe.png"
import f11 from "./home/space-office.jpg"
import f12 from "./home/split-hero.jpg"

export const files: Record<string, StaticImageData> = {
  "about/founder-ayush": f0,
  "about/founder-daksh": f1,
  "home/benefit-ingredients": f2,
  "home/benefit-smart-control": f3,
  "home/benefit-variety": f4,
  "home/diffusers-room": f5,
  "home/hero-poster": f6,
  "home/promo-harvest": f7,
  "home/promo-seasonal": f8,
  "home/promo-whole-home": f9,
  "home/space-cafe": f10,
  "home/space-office": f11,
  "home/split-hero": f12,
}
